heat_template_version: 2018-03-02

description: >
    Create  VM instances servers for CMS Inner Tracker Phase-II 
    test beam analysis

resources:
    group:
        type: OS::Heat::ResourceGroup
        properties:
            count: 10
            resource_def:
                type: OS::Nova::Server
                properties:
                    name: "cmsit-tba0%index%"
                    key_name: lxplus
                    image: 8d4646d6-0f8e-4118-bc04-81192c365e78
                    flavor: m2.large
                    metadata: {"landb-description":"TEST-BEAM EUDET type dockerized analysis server",
                        "landb-os": "LINUX",
                        "landb-mainuser": "CMS-IT-TB-SPS",
                        "landb-responsible": "duarte"
                        }
                    user_data_format: RAW
                    user_data:
                        get_file: user_data_context_mlt.txt

